POST http://localhost:3333/registro
Content-Type: application/json

{
    "contato": "Pai",
    "horario": "16h",
    "duracao": "10min"
}

###

GET http://localhost:3333/registro

###

GET http://localhost:3333/registro?search=Pai

###

PUT http://localhost:3333/registro/6044ec6f-31e0-4b21-b3fc-95bcb16fd316
Content-Type: application/json

{
    "contato": "Mãe",
    "horario": "17h",
    "duracao": "20min"
}

###

DELETE http://localhost:3333/registro/03afebb2-2078-45f5-8898-84c615a7c437