POST http://localhost:3333/telefone
Content-Type: application/json
{
      "Número" :"9964-4446",
      "hora" : "16:44" ,
      "duraçao" : "4:00 minutos",
}
###

GET http://localhost:3333/registro

###

GET http://localhost:3333/registro?search=IFMS

###

PUT http://localhost:3333/telefone/aceb8817-5755-4d12-aebd-532847f7db54
Content-Type: application/json

{
    "nome": "LISTA TELEFONICA ",
    "Número": "9965-4452",
    
}

###

DELETE http://localhost:3333/telefone/aceb8817-5755-4d12-aebd-532847f7db54